# Generated by Django 5.1.3 on 2025-02-13 10:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "light_status",
                    models.CharField(
                        choices=[("RED", "Red Light"), ("GREEN", "Green Light")],
                        default="RED",
                        max_length=5,
                    ),
                ),
                (
                    "last_status_change",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_plate", models.CharField(max_length=10, unique=True)),
                ("owner_name", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=10)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("owner_email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Junction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "last_status_change",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("roads", models.ManyToManyField(to="system.road")),
            ],
        ),
        migrations.CreateModel(
            name="JunctionVehicleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "junction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.junction",
                    ),
                ),
                (
                    "entry_road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.road"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.vehicle"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="junction",
            name="logged_vehicles",
            field=models.ManyToManyField(
                blank=True, through="system.JunctionVehicleLog", to="system.vehicle"
            ),
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("RED_LIGHT", "Running Red Light"),
                            ("SPEEDING", "Speeding"),
                            ("PARKING", "Parking Violation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                ("fine_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "junction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="system.junction",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="system.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrafficAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hour",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                ("vehicle_count", models.IntegerField(default=0)),
                ("peak_status", models.BooleanField(default=False)),
                (
                    "junction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="system.junction",
                    ),
                ),
            ],
            options={
                "unique_together": {("junction", "date", "hour")},
            },
        ),
    ]
