# Generated by Django 5.1.3 on 2025-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_email',
            field=models.CharField(default='unknown@example.com', max_length=100),
        ),
    ]
