# Generated by Django 5.1.2 on 2025-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("CAR", "Car"),
                    ("BUS", "Bus"),
                    ("TRUCK", "Truck"),
                    ("EMERGENCY", "Emergency Vehicle"),
                ],
                default="CAR",
                max_length=10,
            ),
        ),
    ]
