# Generated by Django 5.1.3 on 2025-02-06 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_vehicle_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='junction',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='road',
            name='last_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='road',
            name='light_status',
            field=models.CharField(choices=[('RED', 'Red Light'), ('GREEN', 'Green Light')], default='RED', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_email',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('RED_LIGHT', 'Running Red Light'), ('SPEEDING', 'Speeding'), ('PARKING', 'Parking Violation')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('junction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='system.junction')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='system.vehicle')),
            ],
        ),
    ]
